# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/turboss/Proyectos/VideoVCP/video_vcp/ui/window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setProperty("promptAtExit", False)
        MainWindow.setProperty("promot_on_exit", False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.main_gbox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.main_gbox.setObjectName("main_gbox")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.main_gbox)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.estop_abutton = ActionButton(self.main_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.estop_abutton.sizePolicy().hasHeightForWidth())
        self.estop_abutton.setSizePolicy(sizePolicy)
        self.estop_abutton.setMinimumSize(QtCore.QSize(60, 64))
        self.estop_abutton.setMaximumSize(QtCore.QSize(64, 100))
        self.estop_abutton.setCheckable(True)
        self.estop_abutton.setObjectName("estop_abutton")
        self.horizontalLayout_6.addWidget(self.estop_abutton)
        self.power_abutton = ActionButton(self.main_gbox)
        self.power_abutton.setEnabled(False)
        self.power_abutton.setMinimumSize(QtCore.QSize(60, 64))
        self.power_abutton.setMaximumSize(QtCore.QSize(100, 100))
        self.power_abutton.setCheckable(True)
        self.power_abutton.setObjectName("power_abutton")
        self.horizontalLayout_6.addWidget(self.power_abutton)
        self.horizontalLayout_2.addWidget(self.main_gbox)
        self.mode_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.mode_gbox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.mode_gbox.setObjectName("mode_gbox")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.mode_gbox)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.actionbutton_27 = ActionButton(self.mode_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionbutton_27.sizePolicy().hasHeightForWidth())
        self.actionbutton_27.setSizePolicy(sizePolicy)
        self.actionbutton_27.setMinimumSize(QtCore.QSize(60, 64))
        self.actionbutton_27.setMaximumSize(QtCore.QSize(100, 100))
        self.actionbutton_27.setCheckable(True)
        self.actionbutton_27.setAutoExclusive(True)
        self.actionbutton_27.setObjectName("actionbutton_27")
        self.horizontalLayout_8.addWidget(self.actionbutton_27)
        self.actionbutton_28 = ActionButton(self.mode_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionbutton_28.sizePolicy().hasHeightForWidth())
        self.actionbutton_28.setSizePolicy(sizePolicy)
        self.actionbutton_28.setMinimumSize(QtCore.QSize(60, 64))
        self.actionbutton_28.setMaximumSize(QtCore.QSize(100, 100))
        self.actionbutton_28.setCheckable(True)
        self.actionbutton_28.setAutoExclusive(True)
        self.actionbutton_28.setObjectName("actionbutton_28")
        self.horizontalLayout_8.addWidget(self.actionbutton_28)
        self.actionbutton_29 = ActionButton(self.mode_gbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionbutton_29.sizePolicy().hasHeightForWidth())
        self.actionbutton_29.setSizePolicy(sizePolicy)
        self.actionbutton_29.setMinimumSize(QtCore.QSize(60, 64))
        self.actionbutton_29.setMaximumSize(QtCore.QSize(100, 100))
        self.actionbutton_29.setCheckable(True)
        self.actionbutton_29.setAutoExclusive(True)
        self.actionbutton_29.setObjectName("actionbutton_29")
        self.horizontalLayout_8.addWidget(self.actionbutton_29)
        self.horizontalLayout_2.addWidget(self.mode_gbox)
        self.home_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.home_gbox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.home_gbox.setObjectName("home_gbox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.home_gbox)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.homeall_abutton = ActionButton(self.home_gbox)
        self.homeall_abutton.setMinimumSize(QtCore.QSize(60, 64))
        self.homeall_abutton.setMaximumSize(QtCore.QSize(100, 100))
        self.homeall_abutton.setObjectName("homeall_abutton")
        self.horizontalLayout_3.addWidget(self.homeall_abutton)
        self.horizontalLayout_2.addWidget(self.home_gbox)
        self.part_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.part_gbox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.part_gbox.setObjectName("part_gbox")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.part_gbox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.zero_all_button = MDIButton(self.part_gbox)
        self.zero_all_button.setEnabled(False)
        self.zero_all_button.setMinimumSize(QtCore.QSize(60, 64))
        self.zero_all_button.setMaximumSize(QtCore.QSize(100, 100))
        self.zero_all_button.setObjectName("zero_all_button")
        self.horizontalLayout_5.addWidget(self.zero_all_button)
        self.zero_dbutton = DialogButton(self.part_gbox)
        self.zero_dbutton.setMinimumSize(QtCore.QSize(60, 64))
        self.zero_dbutton.setMaximumSize(QtCore.QSize(100, 100))
        self.zero_dbutton.setObjectName("zero_dbutton")
        self.horizontalLayout_5.addWidget(self.zero_dbutton)
        self.horizontalLayout_2.addWidget(self.part_gbox)
        self.program_gbox = QtWidgets.QGroupBox(self.centralwidget)
        self.program_gbox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.program_gbox.setObjectName("program_gbox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.program_gbox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.open_dbutton = DialogButton(self.program_gbox)
        self.open_dbutton.setMinimumSize(QtCore.QSize(60, 64))
        self.open_dbutton.setMaximumSize(QtCore.QSize(100, 100))
        self.open_dbutton.setObjectName("open_dbutton")
        self.horizontalLayout_7.addWidget(self.open_dbutton)
        self.run_abutton = ActionButton(self.program_gbox)
        self.run_abutton.setMinimumSize(QtCore.QSize(60, 64))
        self.run_abutton.setMaximumSize(QtCore.QSize(100, 100))
        self.run_abutton.setObjectName("run_abutton")
        self.horizontalLayout_7.addWidget(self.run_abutton)
        self.pause_abutton = ActionButton(self.program_gbox)
        self.pause_abutton.setMinimumSize(QtCore.QSize(60, 64))
        self.pause_abutton.setMaximumSize(QtCore.QSize(100, 100))
        self.pause_abutton.setObjectName("pause_abutton")
        self.horizontalLayout_7.addWidget(self.pause_abutton)
        self.stop_abutton = ActionButton(self.program_gbox)
        self.stop_abutton.setMinimumSize(QtCore.QSize(60, 64))
        self.stop_abutton.setMaximumSize(QtCore.QSize(100, 100))
        self.stop_abutton.setObjectName("stop_abutton")
        self.horizontalLayout_7.addWidget(self.stop_abutton)
        self.horizontalLayout_2.addWidget(self.program_gbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setMinimum(-320)
        self.spinBox.setMaximum(320)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_2.addWidget(self.spinBox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setMinimum(-240)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_2.addWidget(self.spinBox_2)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_2.addWidget(self.spinBox_3)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_4.setMaximum(1000)
        self.spinBox_4.setObjectName("spinBox_4")
        self.verticalLayout_2.addWidget(self.spinBox_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.opencvwidget = OpenCVWidget(self.centralwidget)
        self.opencvwidget.setObjectName("opencvwidget")
        self.verticalLayout_3.addWidget(self.opencvwidget)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionReload = QtWidgets.QAction(MainWindow)
        self.actionReload.setObjectName("actionReload")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionHome_X = QtWidgets.QAction(MainWindow)
        self.actionHome_X.setObjectName("actionHome_X")
        self.actionHome_Y = QtWidgets.QAction(MainWindow)
        self.actionHome_Y.setObjectName("actionHome_Y")
        self.actionHome_Z = QtWidgets.QAction(MainWindow)
        self.actionHome_Z.setObjectName("actionHome_Z")
        self.action_EmergencyStop_toggle = QtWidgets.QAction(MainWindow)
        self.action_EmergencyStop_toggle.setObjectName("action_EmergencyStop_toggle")
        self.action_MachinePower_toggle = QtWidgets.QAction(MainWindow)
        self.action_MachinePower_toggle.setObjectName("action_MachinePower_toggle")
        self.actionHome_All = QtWidgets.QAction(MainWindow)
        self.actionHome_All.setObjectName("actionHome_All")
        self.actionRun_Program = QtWidgets.QAction(MainWindow)
        self.actionRun_Program.setObjectName("actionRun_Program")
        self.actionFile1 = QtWidgets.QAction(MainWindow)
        self.actionFile1.setObjectName("actionFile1")
        self.actionReport_Actual_Position = QtWidgets.QAction(MainWindow)
        self.actionReport_Actual_Position.setCheckable(True)
        self.actionReport_Actual_Position.setObjectName("actionReport_Actual_Position")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.action_Mist_toggle = QtWidgets.QAction(MainWindow)
        self.action_Mist_toggle.setCheckable(True)
        self.action_Mist_toggle.setObjectName("action_Mist_toggle")
        self.action_Flood_toggle = QtWidgets.QAction(MainWindow)
        self.action_Flood_toggle.setCheckable(True)
        self.action_Flood_toggle.setObjectName("action_Flood_toggle")
        self.action_program_run = QtWidgets.QAction(MainWindow)
        self.action_program_run.setObjectName("action_program_run")
        self.action_coolant_floodToggle = QtWidgets.QAction(MainWindow)
        self.action_coolant_floodToggle.setCheckable(True)
        self.action_coolant_floodToggle.setObjectName("action_coolant_floodToggle")
        self.actionHalshow = QtWidgets.QAction(MainWindow)
        self.actionHalshow.setObjectName("actionHalshow")
        self.actionHalmeter = QtWidgets.QAction(MainWindow)
        self.actionHalmeter.setObjectName("actionHalmeter")
        self.actionHAL_Scope = QtWidgets.QAction(MainWindow)
        self.actionHAL_Scope.setObjectName("actionHAL_Scope")
        self.actionCalibration = QtWidgets.QAction(MainWindow)
        self.actionCalibration.setObjectName("actionCalibration")
        self.actionOverride_Limits = QtWidgets.QAction(MainWindow)
        self.actionOverride_Limits.setObjectName("actionOverride_Limits")
        self.actionOverride_Limits_2 = QtWidgets.QAction(MainWindow)
        self.actionOverride_Limits_2.setObjectName("actionOverride_Limits_2")
        self.actionRun_From_Line = QtWidgets.QAction(MainWindow)
        self.actionRun_From_Line.setObjectName("actionRun_From_Line")
        self.actionStep = QtWidgets.QAction(MainWindow)
        self.actionStep.setObjectName("actionStep")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionResume = QtWidgets.QAction(MainWindow)
        self.actionResume.setObjectName("actionResume")
        self.actionPause_at_M1 = QtWidgets.QAction(MainWindow)
        self.actionPause_at_M1.setObjectName("actionPause_at_M1")
        self.actionSkip_lines_with = QtWidgets.QAction(MainWindow)
        self.actionSkip_lines_with.setObjectName("actionSkip_lines_with")

        self.retranslateUi(MainWindow)
        self.checkBox.toggled['bool'].connect(self.opencvwidget.enableCrosshairs)
        self.checkBox_2.toggled['bool'].connect(self.opencvwidget.enableEdge)
        self.spinBox.valueChanged['int'].connect(self.opencvwidget.setHorizontalLine)
        self.spinBox_2.valueChanged['int'].connect(self.opencvwidget.setVerticalLine)
        self.spinBox_3.valueChanged['int'].connect(self.opencvwidget.setEdgeMaxThreshold)
        self.spinBox_4.valueChanged['int'].connect(self.opencvwidget.setEdgeMinThreshold)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VideoVCP"))
        self.main_gbox.setTitle(_translate("MainWindow", "MAIN"))
        self.estop_abutton.setText(_translate("MainWindow", "E-STOP"))
        self.estop_abutton.setProperty("actionName", _translate("MainWindow", "machine.estop.toggle"))
        self.power_abutton.setText(_translate("MainWindow", "POWER"))
        self.power_abutton.setProperty("actionName", _translate("MainWindow", "machine.power.toggle"))
        self.mode_gbox.setTitle(_translate("MainWindow", "MODE"))
        self.actionbutton_27.setText(_translate("MainWindow", "MAN"))
        self.actionbutton_27.setProperty("actionName", _translate("MainWindow", "machine.mode.manual"))
        self.actionbutton_27.setProperty("position", _translate("MainWindow", "first"))
        self.actionbutton_27.setProperty("styleClass", _translate("MainWindow", "option"))
        self.actionbutton_28.setText(_translate("MainWindow", "AUTO"))
        self.actionbutton_28.setProperty("actionName", _translate("MainWindow", "machine.mode.auto"))
        self.actionbutton_28.setProperty("styleClass", _translate("MainWindow", "option"))
        self.actionbutton_29.setText(_translate("MainWindow", "MDI"))
        self.actionbutton_29.setProperty("actionName", _translate("MainWindow", "machine.mode.mdi"))
        self.actionbutton_29.setProperty("position", _translate("MainWindow", "last"))
        self.actionbutton_29.setProperty("styleClass", _translate("MainWindow", "option"))
        self.home_gbox.setTitle(_translate("MainWindow", "HOME"))
        self.homeall_abutton.setText(_translate("MainWindow", "ALL"))
        self.homeall_abutton.setProperty("actionName", _translate("MainWindow", "machine.home.all"))
        self.part_gbox.setTitle(_translate("MainWindow", "PART"))
        self.zero_all_button.setText(_translate("MainWindow", "ZERO\n"
"ALL"))
        self.zero_all_button.setProperty("rules", _translate("MainWindow", "[\n"
"    {\n"
"        \"channels\": [\n"
"            {\n"
"                \"url\": \"status:g5x_index\",\n"
"                \"trigger\": true,\n"
"                \"type\": \"int\"\n"
"            }\n"
"        ],\n"
"        \"expression\": \"\",\n"
"        \"name\": \"G5x Index\",\n"
"        \"property\": \"None\"\n"
"    }\n"
"]"))
        self.zero_all_button.setProperty("MDICommand", _translate("MainWindow", "G10 L20 P{ch[0]} X0.0 Y0.0 Z0.0"))
        self.zero_dbutton.setText(_translate("MainWindow", "ZERO"))
        self.zero_dbutton.setProperty("dialogName", _translate("MainWindow", "set_work_offsets"))
        self.program_gbox.setTitle(_translate("MainWindow", "PROGRAM"))
        self.open_dbutton.setText(_translate("MainWindow", "OPEN"))
        self.open_dbutton.setProperty("dialogName", _translate("MainWindow", "open_file"))
        self.run_abutton.setText(_translate("MainWindow", "RUN"))
        self.run_abutton.setProperty("actionName", _translate("MainWindow", "program.run"))
        self.pause_abutton.setText(_translate("MainWindow", "PAUSE"))
        self.pause_abutton.setProperty("actionName", _translate("MainWindow", "program.pause"))
        self.stop_abutton.setText(_translate("MainWindow", "STOP"))
        self.stop_abutton.setProperty("actionName", _translate("MainWindow", "program.abort"))
        self.checkBox.setText(_translate("MainWindow", "Croshairs"))
        self.label.setText(_translate("MainWindow", "Horizontal"))
        self.label_2.setText(_translate("MainWindow", "Vertical"))
        self.checkBox_2.setText(_translate("MainWindow", "Edje detection"))
        self.label_3.setText(_translate("MainWindow", "Max threshold"))
        self.label_4.setText(_translate("MainWindow", "Min threshold"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpen.setText(_translate("MainWindow", "&Open ..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionReload.setText(_translate("MainWindow", "&Reload"))
        self.actionReload.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As ..."))
        self.actionHome_X.setText(_translate("MainWindow", "Home &X"))
        self.actionHome_Y.setText(_translate("MainWindow", "Home &Y"))
        self.actionHome_Z.setText(_translate("MainWindow", "Home &Z"))
        self.action_EmergencyStop_toggle.setText(_translate("MainWindow", "Toggle E-stop"))
        self.action_EmergencyStop_toggle.setShortcut(_translate("MainWindow", "F1"))
        self.action_EmergencyStop_toggle.setProperty("actionName", _translate("MainWindow", "machine.estop.toggle"))
        self.action_MachinePower_toggle.setText(_translate("MainWindow", "Machine Power"))
        self.action_MachinePower_toggle.setShortcut(_translate("MainWindow", "F2"))
        self.action_MachinePower_toggle.setProperty("actionName", _translate("MainWindow", "machine.power.toggle"))
        self.actionHome_All.setText(_translate("MainWindow", "Home All"))
        self.actionHome_All.setShortcut(_translate("MainWindow", "Home"))
        self.actionRun_Program.setText(_translate("MainWindow", "Run Program"))
        self.actionRun_Program.setShortcut(_translate("MainWindow", "R"))
        self.actionRun_Program.setProperty("actionName", _translate("MainWindow", "program.run"))
        self.actionFile1.setText(_translate("MainWindow", "File1"))
        self.actionReport_Actual_Position.setText(_translate("MainWindow", "Report Actual Position"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.action_Mist_toggle.setText(_translate("MainWindow", "Mist"))
        self.action_Mist_toggle.setShortcut(_translate("MainWindow", "F7"))
        self.action_Mist_toggle.setProperty("actionName", _translate("MainWindow", "coolant.mist.toggle"))
        self.action_Flood_toggle.setText(_translate("MainWindow", "Flood"))
        self.action_Flood_toggle.setShortcut(_translate("MainWindow", "F8"))
        self.action_Flood_toggle.setProperty("actionName", _translate("MainWindow", "coolant.flood.toggle"))
        self.action_program_run.setText(_translate("MainWindow", "Run Program"))
        self.action_coolant_floodToggle.setText(_translate("MainWindow", "Flood"))
        self.actionHalshow.setText(_translate("MainWindow", "HAL Show"))
        self.actionHalshow.setProperty("actionName", _translate("MainWindow", "tool.halshow"))
        self.actionHalmeter.setText(_translate("MainWindow", "HAL Meter"))
        self.actionHalmeter.setProperty("actionName", _translate("MainWindow", "tool.halmeter"))
        self.actionHAL_Scope.setText(_translate("MainWindow", "HAL Scope"))
        self.actionHAL_Scope.setProperty("actionName", _translate("MainWindow", "tool.halscope"))
        self.actionCalibration.setText(_translate("MainWindow", "Calibration"))
        self.actionCalibration.setProperty("actionName", _translate("MainWindow", "tool.calibration"))
        self.actionOverride_Limits.setText(_translate("MainWindow", "Override Limits"))
        self.actionOverride_Limits.setProperty("actionName", _translate("MainWindow", "machine.override-limits"))
        self.actionOverride_Limits_2.setText(_translate("MainWindow", "Override Limits"))
        self.actionOverride_Limits_2.setProperty("actionName", _translate("MainWindow", "machine.override-limits"))
        self.actionRun_From_Line.setText(_translate("MainWindow", "Run From Line"))
        self.actionRun_From_Line.setProperty("actionName", _translate("MainWindow", "program.run-from-line"))
        self.actionStep.setText(_translate("MainWindow", "Step"))
        self.actionStep.setShortcut(_translate("MainWindow", "T"))
        self.actionStep.setProperty("actionName", _translate("MainWindow", "program.step"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setShortcut(_translate("MainWindow", "P"))
        self.actionPause.setProperty("actionName", _translate("MainWindow", "program.pause"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setShortcut(_translate("MainWindow", "Esc"))
        self.actionStop.setProperty("actionName", _translate("MainWindow", "program.abort"))
        self.actionResume.setText(_translate("MainWindow", "Resume"))
        self.actionResume.setShortcut(_translate("MainWindow", "S"))
        self.actionResume.setProperty("actionName", _translate("MainWindow", "program.resume"))
        self.actionPause_at_M1.setText(_translate("MainWindow", "Pause at \'M1\'"))
        self.actionPause_at_M1.setProperty("actionName", _translate("MainWindow", "program.optional-stop.toggle"))
        self.actionSkip_lines_with.setText(_translate("MainWindow", "Skip lines with \'/\'"))
        self.actionSkip_lines_with.setProperty("actionName", _translate("MainWindow", "program.block-delete.toggle"))

from qtpyvcp.widgets.button_widgets.action_button import ActionButton
from qtpyvcp.widgets.button_widgets.dialog_button import DialogButton
from qtpyvcp.widgets.button_widgets.mdi_button import MDIButton
from qtpyvcp.widgets.form_widgets.main_window import VCPMainWindow
from qtpyvcp_computer_vision.widgets.opencv_widget import OpenCVWidget
import resources_rc
