# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/turboss/Proyectos/VideoVCP/linuxcnc/configs/sim.video_vcp/hal-widgets.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(243, 277)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        Form.setToolTipDuration(-1)
        Form.setProperty("promptAtExit", False)
        Form.setProperty("promot_on_exit", False)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.xeo_group = HalGroupBox(self.centralwidget)
        self.xeo_group.setCheckable(True)
        self.xeo_group.setObjectName("xeo_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.xeo_group)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.xeo_scale = HalDoubleSpinBox(self.xeo_group)
        self.xeo_scale.setProperty("value", 1.0)
        self.xeo_scale.setObjectName("xeo_scale")
        self.gridLayout.addWidget(self.xeo_scale, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.xeo_group)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.xeo_group)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.xeo_clear = HalButton(self.xeo_group)
        self.xeo_clear.setObjectName("xeo_clear")
        self.gridLayout.addWidget(self.xeo_clear, 3, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.xeo_group)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.xeo_counts = HalQSpinBox(self.xeo_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xeo_counts.sizePolicy().hasHeightForWidth())
        self.xeo_counts.setSizePolicy(sizePolicy)
        self.xeo_counts.setMinimum(-1)
        self.xeo_counts.setMaximum(100)
        self.xeo_counts.setObjectName("xeo_counts")
        self.gridLayout.addWidget(self.xeo_counts, 0, 1, 1, 1)
        self.xeo_request = HalLabel(self.xeo_group)
        self.xeo_request.setObjectName("xeo_request")
        self.gridLayout.addWidget(self.xeo_request, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.xeo_group)
        self.lcd_dro = HalLCDNumber(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_dro.sizePolicy().hasHeightForWidth())
        self.lcd_dro.setSizePolicy(sizePolicy)
        self.lcd_dro.setMinimumSize(QtCore.QSize(225, 75))
        self.lcd_dro.setObjectName("lcd_dro")
        self.verticalLayout_2.addWidget(self.lcd_dro)
        Form.setCentralWidget(self.centralwidget)
        self.actionExit = QtWidgets.QAction(Form)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(Form)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(Form)
        self.actionClose.setObjectName("actionClose")
        self.actionReload = QtWidgets.QAction(Form)
        self.actionReload.setObjectName("actionReload")
        self.actionSave_As = QtWidgets.QAction(Form)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionHome_X = QtWidgets.QAction(Form)
        self.actionHome_X.setObjectName("actionHome_X")
        self.actionHome_Y = QtWidgets.QAction(Form)
        self.actionHome_Y.setObjectName("actionHome_Y")
        self.actionHome_Z = QtWidgets.QAction(Form)
        self.actionHome_Z.setObjectName("actionHome_Z")
        self.action_EmergencyStop_toggle = QtWidgets.QAction(Form)
        self.action_EmergencyStop_toggle.setObjectName("action_EmergencyStop_toggle")
        self.action_MachinePower_toggle = QtWidgets.QAction(Form)
        self.action_MachinePower_toggle.setObjectName("action_MachinePower_toggle")
        self.actionHome_All = QtWidgets.QAction(Form)
        self.actionHome_All.setObjectName("actionHome_All")
        self.actionRun_Program = QtWidgets.QAction(Form)
        self.actionRun_Program.setObjectName("actionRun_Program")
        self.actionFile1 = QtWidgets.QAction(Form)
        self.actionFile1.setObjectName("actionFile1")
        self.actionReport_Actual_Position = QtWidgets.QAction(Form)
        self.actionReport_Actual_Position.setCheckable(True)
        self.actionReport_Actual_Position.setObjectName("actionReport_Actual_Position")
        self.actionTest = QtWidgets.QAction(Form)
        self.actionTest.setObjectName("actionTest")
        self.action_Mist_toggle = QtWidgets.QAction(Form)
        self.action_Mist_toggle.setCheckable(True)
        self.action_Mist_toggle.setObjectName("action_Mist_toggle")
        self.action_Flood_toggle = QtWidgets.QAction(Form)
        self.action_Flood_toggle.setCheckable(True)
        self.action_Flood_toggle.setObjectName("action_Flood_toggle")
        self.action_program_run = QtWidgets.QAction(Form)
        self.action_program_run.setObjectName("action_program_run")
        self.action_coolant_floodToggle = QtWidgets.QAction(Form)
        self.action_coolant_floodToggle.setCheckable(True)
        self.action_coolant_floodToggle.setObjectName("action_coolant_floodToggle")
        self.actionHalshow = QtWidgets.QAction(Form)
        self.actionHalshow.setObjectName("actionHalshow")
        self.actionHalmeter = QtWidgets.QAction(Form)
        self.actionHalmeter.setObjectName("actionHalmeter")
        self.actionHAL_Scope = QtWidgets.QAction(Form)
        self.actionHAL_Scope.setObjectName("actionHAL_Scope")
        self.actionCalibration = QtWidgets.QAction(Form)
        self.actionCalibration.setObjectName("actionCalibration")
        self.actionOverride_Limits = QtWidgets.QAction(Form)
        self.actionOverride_Limits.setObjectName("actionOverride_Limits")
        self.actionOverride_Limits_2 = QtWidgets.QAction(Form)
        self.actionOverride_Limits_2.setObjectName("actionOverride_Limits_2")
        self.actionRun_From_Line = QtWidgets.QAction(Form)
        self.actionRun_From_Line.setObjectName("actionRun_From_Line")
        self.actionStep = QtWidgets.QAction(Form)
        self.actionStep.setObjectName("actionStep")
        self.actionPause = QtWidgets.QAction(Form)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(Form)
        self.actionStop.setObjectName("actionStop")
        self.actionResume = QtWidgets.QAction(Form)
        self.actionResume.setObjectName("actionResume")
        self.actionPause_at_M1 = QtWidgets.QAction(Form)
        self.actionPause_at_M1.setObjectName("actionPause_at_M1")
        self.actionSkip_lines_with = QtWidgets.QAction(Form)
        self.actionSkip_lines_with.setObjectName("actionSkip_lines_with")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QtPyVCP Demo - Mini VCP"))
        self.xeo_group.setTitle(_translate("Form", "X Axis E-Offset"))
        self.label_3.setText(_translate("Form", "Scale:"))
        self.label.setText(_translate("Form", "Counts:"))
        self.xeo_clear.setText(_translate("Form", "Clear E-Offset"))
        self.label_4.setText(_translate("Form", "Request:"))
        self.actionExit.setText(_translate("Form", "Exit"))
        self.actionOpen.setText(_translate("Form", "&Open ..."))
        self.actionOpen.setShortcut(_translate("Form", "O"))
        self.actionClose.setText(_translate("Form", "Close"))
        self.actionReload.setText(_translate("Form", "&Reload"))
        self.actionReload.setShortcut(_translate("Form", "Ctrl+R"))
        self.actionSave_As.setText(_translate("Form", "Save As ..."))
        self.actionHome_X.setText(_translate("Form", "Home &X"))
        self.actionHome_Y.setText(_translate("Form", "Home &Y"))
        self.actionHome_Z.setText(_translate("Form", "Home &Z"))
        self.action_EmergencyStop_toggle.setText(_translate("Form", "Toggle E-stop"))
        self.action_EmergencyStop_toggle.setShortcut(_translate("Form", "F1"))
        self.action_EmergencyStop_toggle.setProperty("actionName", _translate("Form", "machine.estop.toggle"))
        self.action_MachinePower_toggle.setText(_translate("Form", "Machine Power"))
        self.action_MachinePower_toggle.setShortcut(_translate("Form", "F2"))
        self.action_MachinePower_toggle.setProperty("actionName", _translate("Form", "machine.power.toggle"))
        self.actionHome_All.setText(_translate("Form", "Home All"))
        self.actionRun_Program.setText(_translate("Form", "Run Program"))
        self.actionRun_Program.setShortcut(_translate("Form", "R"))
        self.actionRun_Program.setProperty("actionName", _translate("Form", "program.run"))
        self.actionFile1.setText(_translate("Form", "File1"))
        self.actionReport_Actual_Position.setText(_translate("Form", "Report Actual Position"))
        self.actionTest.setText(_translate("Form", "Test"))
        self.action_Mist_toggle.setText(_translate("Form", "Mist"))
        self.action_Mist_toggle.setShortcut(_translate("Form", "F7"))
        self.action_Mist_toggle.setProperty("actionName", _translate("Form", "coolant.mist.toggle"))
        self.action_Flood_toggle.setText(_translate("Form", "Flood"))
        self.action_Flood_toggle.setShortcut(_translate("Form", "F8"))
        self.action_Flood_toggle.setProperty("actionName", _translate("Form", "coolant.flood.toggle"))
        self.action_program_run.setText(_translate("Form", "Run Program"))
        self.action_coolant_floodToggle.setText(_translate("Form", "Flood"))
        self.actionHalshow.setText(_translate("Form", "HAL Show"))
        self.actionHalshow.setProperty("actionName", _translate("Form", "tool.halshow"))
        self.actionHalmeter.setText(_translate("Form", "HAL Meter"))
        self.actionHalmeter.setProperty("actionName", _translate("Form", "tool.halmeter"))
        self.actionHAL_Scope.setText(_translate("Form", "HAL Scope"))
        self.actionHAL_Scope.setProperty("actionName", _translate("Form", "tool.halscope"))
        self.actionCalibration.setText(_translate("Form", "Calibration"))
        self.actionCalibration.setProperty("actionName", _translate("Form", "tool.calibration"))
        self.actionOverride_Limits.setText(_translate("Form", "Override Limits"))
        self.actionOverride_Limits.setProperty("actionName", _translate("Form", "machine.override-limits"))
        self.actionOverride_Limits_2.setText(_translate("Form", "Override Limits"))
        self.actionOverride_Limits_2.setProperty("actionName", _translate("Form", "machine.override-limits"))
        self.actionRun_From_Line.setText(_translate("Form", "Run From Line"))
        self.actionRun_From_Line.setProperty("actionName", _translate("Form", "program.run-from-line"))
        self.actionStep.setText(_translate("Form", "Step"))
        self.actionStep.setShortcut(_translate("Form", "T"))
        self.actionStep.setProperty("actionName", _translate("Form", "program.step"))
        self.actionPause.setText(_translate("Form", "Pause"))
        self.actionPause.setShortcut(_translate("Form", "P"))
        self.actionPause.setProperty("actionName", _translate("Form", "program.pause"))
        self.actionStop.setText(_translate("Form", "Stop"))
        self.actionStop.setShortcut(_translate("Form", "Esc"))
        self.actionStop.setProperty("actionName", _translate("Form", "program.abort"))
        self.actionResume.setText(_translate("Form", "Resume"))
        self.actionResume.setShortcut(_translate("Form", "S"))
        self.actionResume.setProperty("actionName", _translate("Form", "program.resume"))
        self.actionPause_at_M1.setText(_translate("Form", "Pause at \'M1\'"))
        self.actionPause_at_M1.setProperty("actionName", _translate("Form", "program.optional-stop.toggle"))
        self.actionSkip_lines_with.setText(_translate("Form", "Skip lines with \'/\'"))
        self.actionSkip_lines_with.setProperty("actionName", _translate("Form", "program.block-delete.toggle"))

from qtpyvcp.widgets.form_widgets.main_window import VCPMainWindow
from qtpyvcp.widgets.hal_widgets.hal_button import HalButton
from qtpyvcp.widgets.hal_widgets.hal_double_spinbox import HalDoubleSpinBox
from qtpyvcp.widgets.hal_widgets.hal_groupbox import HalGroupBox
from qtpyvcp.widgets.hal_widgets.hal_label import HalLabel
from qtpyvcp.widgets.hal_widgets.hal_lcd import HalLCDNumber
from qtpyvcp.widgets.hal_widgets.hal_spinbox import HalQSpinBox
